
import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class Perfil extends javax.swing.JFrame {
ImageIcon auxicon = null;
    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
        head.setIcon(new ImageIcon("E:\\SENAC 2013¹\\ES2\\InstaBookJAVA\\Imagens\\head.gif")); 
        auxicon = new ImageIcon(Inicial.Uaux.avatar);
        Lavatar.setIcon(auxicon);
        //Lnome.setText(Inicial.Uaux.getNomeUsuario());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        BenviarFoto = new javax.swing.JButton();
        Lnome = new javax.swing.JLabel();
        Lavatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PhotoShoot");
        setPreferredSize(new java.awt.Dimension(750, 500));

        head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headMouseClicked(evt);
            }
        });

        BenviarFoto.setText("Enviar Foto");
        BenviarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenviarFotoActionPerformed(evt);
            }
        });

        Lnome.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Lavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BenviarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lnome)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BenviarFoto)
                        .addGap(17, 17, 17)
                        .addComponent(Lnome))
                    .addComponent(Lavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMouseClicked
        //this.dispose();
        //Perfil.setVisible(true);
    }//GEN-LAST:event_headMouseClicked
          Image aux = null;
          

    private void BenviarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenviarFotoActionPerformed
          Image aux = null;
        JOptionPane.showMessageDialog(rootPane, head, "Escolha uma foto para seu Avatar", WIDTH);
        JFileChooser foto = new JFileChooser();
        
                    if (foto.showOpenDialog(null)== JFileChooser.APPROVE_OPTION){
                        JOptionPane.showMessageDialog(null, "mas que beleza einh?!?!");
                        //aux = Image.class.cast(foto.getSelectedFile());
                        
                        try{
                         aux = ImageIO.read(foto.getSelectedFile());                                                 
                         Inicial.Uaux.setAvatar(aux);
                        }
                        catch(Exception e){
                            e.printStackTrace();
                        }
                        
                    } 
    }//GEN-LAST:event_BenviarFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BenviarFoto;
    private javax.swing.JLabel Lavatar;
    private javax.swing.JLabel Lnome;
    private javax.swing.JLabel head;
    // End of variables declaration//GEN-END:variables
}
